### PR TITLE
Add and run formatter.

### PR DESCRIPTION
**Pull request by dj2**
# Summary | Résumé

This adds the prettier formatter and runs over the various files in the
repository.

### CODE REVIEW

**Comment by maxneuvians** [comment]
Could we automate this as part of CI - something like https://github.com/marketplace/actions/prettier-action

**Comment by dj2** [comment]
I think we should get an action in place, but would prefer to do that as a self contained PR. Would you be OK with landing the infrastructure and initial re-formatting and then a second PR to add the GH action stuff?

**Comment by maxneuvians** [comment]
Works for me!

**Review by maxneuvians — APPROVED** [review]
🎉

**Review by wmoussa-cds — APPROVED** [review]

**Pull request merged**
